//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.06 at 10:00:30 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://keepcalm.ch/web/country/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.keepcalm.web.country.ws;
